version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 Asignatura_DsS_2024A.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Password01

volumes:
  postgres_data:
