# Generated by Django 5.0.7 on 2024-08-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='supera_record',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidades_vendidas',
        ),
    ]
